# Generated by Django 3.0.5 on 2021-01-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='last_login_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='registered_at',
        ),
    ]
