# Generated by Django 3.0.5 on 2021-03-16 13:16

from django.db import migrations, models
import gridfs_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_proof',
            field=models.FileField(blank=True, null=True, storage=gridfs_storage.storage.GridFSStorage(collection='id_proof'), upload_to=''),
        ),
    ]
