# Generated by Django 3.0.5 on 2021-03-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210224_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rzp_customer_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
