# Generated by Django 3.0.5 on 2021-02-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210126_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
