# Generated by Django 3.0.5 on 2021-03-23 18:12

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, default='', max_length=500)),
                ('parent_id', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='page-images/')),
                ('meta_title', models.CharField(max_length=50)),
                ('meta_desc', models.CharField(blank=True, default='', max_length=500)),
                ('meta_keywords', models.CharField(max_length=100)),
                ('multi_images', models.ImageField(upload_to='page-images/')),
                ('slug', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
