# Generated by Django 3.0.5 on 2021-03-23 18:12

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=50)),
                ('image_title', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, default='', max_length=500)),
                ('meta_title', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slider-images/')),
            ],
        ),
    ]
