# Generated by Django 3.0.5 on 2021-02-19 15:26

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('duration', models.CharField(choices=[('y', 'Yearly'), ('q', 'Quarterly'), ('m', 'Monthly'), ('w', 'Weekly'), ('d', 'Daily')], default='m', max_length=10)),
                ('letters_count', models.IntegerField()),
                ('bureaus_count', models.IntegerField(blank=True, default=1)),
                ('desc', models.TextField(blank=True, default='')),
                ('status', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
