# Generated by Django 3.0.5 on 2021-03-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='rzp_plan_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
