# Generated by Django 3.0.5 on 2021-03-23 18:12

import api.letter.models
import datetime
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('short_desc', models.CharField(blank=True, default='', max_length=500)),
                ('content', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LetterBureau',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('letter_client_url', models.URLField(blank=True, default='', max_length=500)),
                ('bureau_url', models.URLField(blank=True, default='', max_length=500)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='letters/')),
                ('last_run_at', models.DateTimeField(blank=True, default=api.letter.models.get_default_date, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, default=api.letter.models.get_default_date, null=True)),
                ('cron_expression', models.CharField(default='0 0 1 1 0', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LetterClient',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('account_no', models.CharField(max_length=50)),
                ('creditor_name', models.CharField(max_length=100)),
                ('mention_date', models.DateField(blank=True, default=datetime.date.today)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stop_at', models.DateTimeField(blank=True, null=True)),
                ('letter_sub_url', models.URLField(blank=True, default='', max_length=500)),
                ('letter_url', models.URLField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LetterSubscription',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('letters_count', models.IntegerField(default=1)),
                ('initial_letters_count', models.IntegerField(default=1)),
                ('bureaus_count', models.IntegerField(blank=True, default=1)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
