# Generated by Django 3.0.5 on 2021-02-21 09:36

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterClient',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('account_no', models.CharField(max_length=50)),
                ('creditor_name', models.CharField(max_length=100)),
                ('mention_date', models.DateTimeField()),
                ('pdf_file', models.FileField(upload_to='letters_client/')),
                ('status', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stop_at', models.DateTimeField(blank=True, null=True)),
                ('letter_sub_url', models.URLField(blank=True, default='', max_length=500)),
                ('letter_url', models.URLField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
