# Generated by Django 3.0.5 on 2021-02-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterclient',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='letterbureau',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='letters_client/'),
        ),
    ]
