# Generated by Django 3.0.5 on 2021-02-21 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_letterclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterclient',
            name='mention_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='letterclient',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='letters_client/'),
        ),
    ]
