# Generated by Django 3.0.5 on 2021-02-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_auto_20210227_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterbureau',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='letters/'),
        ),
    ]
