# Generated by Django 3.0.5 on 2021-02-21 16:07

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0003_auto_20210221_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterBureau',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('letter_client_url', models.URLField(blank=True, default='', max_length=500)),
                ('bureau_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
