# Generated by Django 3.0.5 on 2021-02-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0004_letterbureau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
