# Generated by Django 3.0.5 on 2021-02-22 16:48

import datetime
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('sub_status', models.BooleanField(default=True)),
                ('period_start', models.DateTimeField(auto_now_add=True)),
                ('period_end', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 24, 22, 18, 40, 360035))),
                ('billing_address', models.TextField(default='')),
                ('unsubscribe_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_url', models.URLField(blank=True, default='', max_length=500)),
                ('pricing_url', models.URLField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
