# Generated by Django 3.0.5 on 2021-03-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='rzp_sub_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
