# Generated by Django 3.0.5 on 2021-02-22 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20210222_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='period_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 24, 17, 1, 44, 288754, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='unsubscribe_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 24, 17, 1, 44, 288754, tzinfo=utc)),
        ),
    ]
