# Generated by Django 3.0.5 on 2021-02-22 17:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20210222_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='client_url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='period_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 24, 17, 4, 28, 135729, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='pricing_url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='unsubscribe_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 24, 17, 4, 28, 135729, tzinfo=utc)),
        ),
    ]
