# Generated by Django 3.0.5 on 2021-02-25 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20210224_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='period_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 27, 17, 35, 29, 997771, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='unsubscribe_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 27, 17, 35, 29, 997771, tzinfo=utc)),
        ),
    ]
