# Generated by Django 3.0.5 on 2021-02-28 06:29

import api.subscription.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_auto_20210227_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='period_end',
            field=models.DateTimeField(blank=True, default=api.subscription.models.get_default_date),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='unsubscribe_date',
            field=models.DateTimeField(blank=True, default=api.subscription.models.get_default_date),
        ),
    ]
